language: ruby
rvm:
  - 1.8.7
  - 2.0.0
  - 2.1.9
env:
  global:
    - SPEC_OPTS="-fd"
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3"
    - PUPPET_VERSION="~> 4"
  gemfile:
    - .gemfile
    - .gemfile-18
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      gemfile: .gemfile
    - rvm: 2.1.9
      gemfile: .gemfile
  include:
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4"
notifications:
  email: false
script:
  - cat .gemfile.lock
  - bundle exec rake spec
before_script:
  - mkdir -p ~/.facter/facts.d
  - echo "user_ssh_pubkey=not_a_user" >> ~/.facter/facts.d/user_ssh_pubkey.txt
  - facter user_ssh_pubkey
